version: 0.2

phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - echo log in to Amazon ECR...
      - aws --version
      - echo $AWS_DEFAULT_REGION
      - echo "$(aws ecr get-login-password --region $AWS_DEFAULT_REGION)" | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER-$IMAGE_SUFFFIX .
      - docker tag $IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:v1.$CODEBUILD_BUILD_NUMBER-$IMAGE_SUFFFIX

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:v1.$CODEBUILD_BUILD_NUMBER-$IMAGE_SUFFFIX
      - mkdir ImageDetail
      - cd ImageDetail
      - echo "[{\"imageUri\":\"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:v1.$CODEBUILD_BUILD_NUMBER-$IMAGE_SUFFFIX\", \"name\":\"feeld-core-api\"}]" > imagedefinitions.json
      #- echo write definitions file...
      #- printf '[{"name":"exp-code-pipeline","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      #- aws lambda invoke --function-name pipeline-task-version-upgrade output.txt
      #- aws s3 cp s3://s3bucketcodepiplinesdata/application-pipeline/build_outp/appspec.yml appspec.yaml
artifacts:
  files:
    - imagedefinitions.json
  name: build_output
  base-directory: ImageDetail
  secondary-artifacts:
    build_output:
      files:
        - ImageDetail/imagedefinitions.json
      name: build_output
